// French is the base dictionary; other locales overlay only the keys they
// translate, falling back to French for the rest. `applyLanguage` mutates the
// shared `S` in place and the root re-mounts, so every `S.xxx` call site picks
// up the new language without a per-file refactor.
const fr = {
  appName: 'iSecure',
  tabMessages: 'Messages',
  tabContacts: 'Contacts',
  tabSettings: 'Réglages',
  // Tabs
  discussions: 'Discussions',
  contacts: 'Contacts',
  settings: 'Paramètres',
  // Discussions screen
  searchConversation: 'Rechercher une conversation',
  newMessage: 'Nouveau message',
  selectMessages: 'Sélectionner des messages',
  notes: 'Notes',
  showKeyIndicator: 'Afficher l\'indicateur de clé',
  clearDiscussions: 'Nettoyer les discussions',
  blockedContacts: 'Contacts bloqués',
  noConversations: 'Aucune conversation',
  startFirstConversation: 'Commencez votre première conversation sécurisée',
  // Contacts screen
  searchContact: 'Rechercher un contact',
  addContact: 'Ajouter un contact',
  allContactsImported: 'Tous les contacts importés',
  importContacts: 'Importer les contacts',
  noContacts: 'Aucun contact',
  addFirstContacts: 'Ajoutez vos premiers contacts pour commencer.',
  // Contact detail
  contactCard: 'Fiche contact',
  shareContact: 'Partager le contact',
  modify: 'Modifier',
  ovConversation: 'Conversation OV',
  block: 'Bloquer',
  delete: 'Supprimer',
  // Chat screen
  writeMessage: 'Écris un message...',
  readMore: 'Lire la suite',
  encryptionActive: 'Chiffrement actif',
  encryptionInactive: 'Chiffrement inactif',
  secureConversation: 'Sécuriser la conversation',
  // Pairing modal
  authorizeIncomingPairing: 'Autoriser un pairing entrant',
  activateBeforeOperation: 'Activez avant de lancer l\'opération.',
  pairingDescription: 'Créez une clé de chiffrement partagée avec ce contact. À faire à deux, en direct, en vous appelant.',
  howItWorks: 'Comment ça marche',
  technicalDetails: 'Détails techniques',
  send: 'Envoyer',
  receive: 'Recevoir',
  // Key required dialog
  keyRequired: '🔐 Clé de chiffrement requise',
  keyRequiredDescription: 'Pour chiffrer vos messages, vous devez d\'abord générer une clé de chiffrement dans l\'onglet Contacts.',
  ok: 'OK',
  cancel: 'Annuler',
  confirm: 'Confirmer',
  // Settings - General
  general: 'Générales',
  appLanguage: 'Langue de l\'application',
  smsDefaultAuto: 'SMS par défaut auto',
  smsService: 'Service SMS',
  vibration: 'Vibration',
  notificationPreview: 'Aperçu notifications',
  filePerformance: 'Performances fichiers',
  // Settings - Connection
  connection: 'Connexion',
  loginPassword: 'Mot de passe de connexion',
  panicPassword: 'Mot de passe panic mode',
  panicKeys: 'Panic clés',
  autoDestruction: 'Destruction automatique',
  verifyPassword: 'Vérifier mot de passe',
  myPhoneNumber: 'Mon numéro de téléphone',
  // Settings - Security
  security: 'Sécurité',
  ephemeralMessages: 'Messages éphémères',
  ovnyMode: 'Chiffrement forcé',
  fortressMode: 'Mode Forteresse',
  activateBase64: 'Activer Base64',
  activateBase36: 'Activer Base36',
  autoLock: 'Verrouillage automatique',
  antiScreenCapture: 'Anti-capture d\'écran',
  // Settings - Assistance
  assistance: 'Assistance',
  rcsReception: 'Réception des messages (RCS)',
  help: 'Aide',
  toKnow: 'À savoir',
  permissions: 'Permissions',
  privacyPolicy: 'Politique de confidentialité',
  about: 'À propos',
  termsOfUse: 'Conditions générales d\'utilisation',
  // Universal encryption
  universalEncryption: 'Chiffrement universel',
  universalDecryption: 'Déchiffrement universel',
  encryptMessage: 'Chiffrer un message',
  decryptMessage: 'Déchiffrer un message',
  encryptFile: 'Chiffrer un fichier',
  decryptFile: 'Déchiffrer un fichier',
  // Onboarding
  onboarding1Title: 'Messagerie chiffrée de bout en bout',
  onboarding1Desc: 'Vos messages sont chiffrés localement avant d\'être envoyés par SMS. Aucun serveur, aucun compte.',
  onboarding2Title: 'Sans compte, sans serveur',
  onboarding2Desc: 'iSecure fonctionne 100% hors ligne. Seul un mot de passe, une clé de chiffrement et un contact suffisent.',
  onboarding3Title: 'Gérez vos contacts sécurisés',
  onboarding3Desc: 'Ajoutez vos contacts et échangez des clés de chiffrement pour des conversations totalement privées.',
  next: 'Suivant',
  getStarted: 'Commencer',
  skip: 'Passer',
  // Login
  loginTitle: 'iSecure',
  loginSubtitle: 'Sécurité, innovation et intelligence artificielle',
  enterPassword: 'Entrez votre mot de passe',
  password: 'Mot de passe',
  passwordPlaceholder: 'Mot de passe (6 caractères minimum)',
  unlock: 'Déverrouiller',
  forgotPassword: 'Mot de passe oublié ?',
  // Phone setup
  phoneSetupTitle: 'Votre numéro de téléphone',
  phoneSetupDesc: 'Entrez votre numéro pour que vos contacts puissent vous identifier.',
  phoneNumber: 'Numéro de téléphone',
  validate: 'Valider',
  // Notes
  notesTitle: 'Notes chiffrées',
  newNote: 'Nouvelle note',
  // Key management
  keyAvailable: 'Clé disponible',
  keyNotConfigured: 'Clé non configurée',
  keyCorrupted: 'Clé corrompue',
  keyMissing: 'Clé manquante',
  keySavedSuccess: 'Clé sauvegardée avec succès.',
  keyRegeneratedSuccess: 'Clé régénérée avec succès',
  keyDeletedSuccess: 'Clé supprimée avec succès.',
  keysAvailable: 'Clés disponibles: {count}',
  // Encryption/Decryption
  encryptionFailed: 'Le chiffrement du message a échoué. Veuillez réessayer.',
  decryptionFailed: 'Le déchiffrement du message a échoué.',
  // QR code
  scanQrCode: 'Scanner un QR code',
  generateQrCode: 'Générer un QR code',
  qrCodeInvalid: 'Ce QR Code n\'est pas valide.',
  // Misc
  loading: 'Chargement...',
  error: 'Erreur',
  success: 'Succès',
  warning: 'Avertissement',
  close: 'Fermer',
  save: 'Sauvegarder',
  back: 'Retour',
  enabled: 'Activé',
  disabled: 'Désactivé',
  on: 'ON',
  off: 'OFF',
  call: 'Appeler',
  copy: 'Copier',
  share: 'Partager',
  export: 'Exporter',
  import: 'Importer',
  copiedToClipboard: 'Copié dans le presse-papiers',
  // Security warnings
  securityWarning: 'Avertissement de sécurité',
  panicModeActivated: 'Mode Panic activé',
  panicModeDescription: 'En cas de contrainte, le mode panic permet d\'effacer toutes vos données immédiatement.',
  destroyAll: 'Tout détruire',
  // Time formats
  today: 'Aujourd\'hui',
  yesterday: 'Hier',
};

// English overlay — the user-facing keys actually rendered via S.xxx.
const en: Partial<typeof fr> = {
  tabMessages: 'Messages',
  tabContacts: 'Contacts',
  tabSettings: 'Settings',
  contacts: 'Contacts',
  newMessage: 'New message',
  notes: 'Notes',
  blockedContacts: 'Blocked contacts',
  noConversations: 'No conversations',
  searchContact: 'Search a contact',
  addContact: 'Add contact',
  notesTitle: 'Encrypted notes',
  newNote: 'New note',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  copy: 'Copy',
  modify: 'Edit',
  block: 'Block',
  error: 'Error',
  loading: 'Loading…',
  send: 'Send',
  receive: 'Receive',
  next: 'Next',
  skip: 'Skip',
  getStarted: 'Get started',
  find: 'Search',
  map: 'Map',
  encryptMessage: 'Encrypt message',
  decryptMessage: 'Decrypt message',
  encryptFile: 'Encrypt file',
  decryptFile: 'Decrypt file',
  encryptionFailed: 'Encryption failed',
  decryptionFailed: 'Decryption failed',
  universalEncryption: 'Universal encryption',
  ovConversation: 'Encrypted conversation',
  contactCard: 'Contact card',
  shareContact: 'Share contact',
  pairingDescription: 'Create a shared key with this contact. Do it together, live, on a call.',
  onboarding1Title: 'End-to-end encryption',
  onboarding1Desc: 'Your messages are encrypted on-device before being sent by SMS. No server, no account.',
  onboarding2Title: '100% offline',
  onboarding2Desc: 'iSecure works fully offline. A password, an encryption key and a contact are all you need.',
  onboarding3Title: 'Post-quantum security',
  onboarding3Desc: 'Hybrid ML-KEM-768 + X25519 key exchange, resistant to quantum computers.',
};

const overlays: Record<string, Partial<typeof fr>> = { fr: {}, en };

// Mutable shared dictionary consumed everywhere as `S.xxx`.
export const S: typeof fr = { ...fr };

export function applyLanguage(code: string) {
  Object.assign(S, fr, overlays[code] ?? {});
}
