// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.ov_core

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_ov_core_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_ov_core_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "ov_core"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}














































































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "ov_core")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
        
    }

    fun uniffi_ov_core_fn_func_complete_pairing_a(`keypairHex`: RustBuffer.ByValue,`bSms`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_decrypt_file(`keyHex`: RustBuffer.ByValue,`ovBytes`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_derive_from_password(`password`: RustBuffer.ByValue,`saltHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_derive_key_pool(`masterHex`: RustBuffer.ByValue,`count`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_derive_sas(`sharedHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_encrypt_file(`keyHex`: RustBuffer.ByValue,`content`: RustBuffer.ByValue,`filename`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_open_message(`poolKeyHex`: RustBuffer.ByValue,`payload`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_ov36_decode(`msg`: RustBuffer.ByValue,`contactKeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_ov36_encode(`plaintext`: RustBuffer.ByValue,`contactKeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_ov_build_ovpk(`session`: RustBuffer.ByValue,`role`: RustBuffer.ByValue,`mlkemPkHex`: RustBuffer.ByValue,`x25519PkHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_ov_decode_ov36(`msg`: RustBuffer.ByValue,`indexCharset`: RustBuffer.ByValue,`specialCharset`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_ov_derive_charset(`base`: RustBuffer.ByValue,`seedA`: RustBuffer.ByValue,`seedB`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_ov_derive_contact_key(`sharedSecretHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_ov_encode_ov36(`keyIndex`: Int,`payload`: RustBuffer.ByValue,`indexCharset`: RustBuffer.ByValue,`specialCharset`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_ov_hybrid_respond(`ovpkSms`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_ov_pairing_announce(`ovpkMsg`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_ov_pairing_finish(`stateHex`: RustBuffer.ByValue,`ovbBMsg`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_ov_parse_ovpk(`msg`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_ov_respond_pairing(`mlkemEkHex`: RustBuffer.ByValue,`x25519PubHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_parse_chunk(`sms`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_peek_key_index(`payload`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun uniffi_ov_core_fn_func_random_key_hex(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_respond_pairing_b(`aSms`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_seal_message(`poolKeyHex`: RustBuffer.ByValue,`keyIndex`: Int,`plaintext`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_split_into_chunks(`payload`: RustBuffer.ByValue,`msgId`: RustBuffer.ByValue,`maxLen`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_ov_core_fn_func_start_pairing_a(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_ov_core_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_ov_core_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_ov_core_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_ov_core_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_ov_core_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_ov_core_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_ov_core_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_ov_core_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_ov_core_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_ov_core_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_ov_core_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_ov_core_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_ov_core_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_ov_core_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_ov_core_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_ov_core_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_ov_core_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_ov_core_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_ov_core_checksum_func_complete_pairing_a(
    ): Short
    fun uniffi_ov_core_checksum_func_decrypt_file(
    ): Short
    fun uniffi_ov_core_checksum_func_derive_from_password(
    ): Short
    fun uniffi_ov_core_checksum_func_derive_key_pool(
    ): Short
    fun uniffi_ov_core_checksum_func_derive_sas(
    ): Short
    fun uniffi_ov_core_checksum_func_encrypt_file(
    ): Short
    fun uniffi_ov_core_checksum_func_open_message(
    ): Short
    fun uniffi_ov_core_checksum_func_ov36_decode(
    ): Short
    fun uniffi_ov_core_checksum_func_ov36_encode(
    ): Short
    fun uniffi_ov_core_checksum_func_ov_build_ovpk(
    ): Short
    fun uniffi_ov_core_checksum_func_ov_decode_ov36(
    ): Short
    fun uniffi_ov_core_checksum_func_ov_derive_charset(
    ): Short
    fun uniffi_ov_core_checksum_func_ov_derive_contact_key(
    ): Short
    fun uniffi_ov_core_checksum_func_ov_encode_ov36(
    ): Short
    fun uniffi_ov_core_checksum_func_ov_hybrid_respond(
    ): Short
    fun uniffi_ov_core_checksum_func_ov_pairing_announce(
    ): Short
    fun uniffi_ov_core_checksum_func_ov_pairing_finish(
    ): Short
    fun uniffi_ov_core_checksum_func_ov_parse_ovpk(
    ): Short
    fun uniffi_ov_core_checksum_func_ov_respond_pairing(
    ): Short
    fun uniffi_ov_core_checksum_func_parse_chunk(
    ): Short
    fun uniffi_ov_core_checksum_func_peek_key_index(
    ): Short
    fun uniffi_ov_core_checksum_func_random_key_hex(
    ): Short
    fun uniffi_ov_core_checksum_func_respond_pairing_b(
    ): Short
    fun uniffi_ov_core_checksum_func_seal_message(
    ): Short
    fun uniffi_ov_core_checksum_func_split_into_chunks(
    ): Short
    fun uniffi_ov_core_checksum_func_start_pairing_a(
    ): Short
    fun ffi_ov_core_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_ov_core_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_ov_core_checksum_func_complete_pairing_a() != 43950.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_decrypt_file() != 15160.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_derive_from_password() != 44113.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_derive_key_pool() != 54545.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_derive_sas() != 8663.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_encrypt_file() != 29703.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_open_message() != 28413.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_ov36_decode() != 51059.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_ov36_encode() != 47624.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_ov_build_ovpk() != 41293.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_ov_decode_ov36() != 64240.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_ov_derive_charset() != 33227.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_ov_derive_contact_key() != 58581.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_ov_encode_ov36() != 48743.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_ov_hybrid_respond() != 6722.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_ov_pairing_announce() != 60811.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_ov_pairing_finish() != 38620.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_ov_parse_ovpk() != 48723.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_ov_respond_pairing() != 21257.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_parse_chunk() != 46397.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_peek_key_index() != 51241.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_random_key_hex() != 35179.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_respond_pairing_b() != 34416.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_seal_message() != 63839.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_split_into_chunks() != 63599.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ov_core_checksum_func_start_pairing_a() != 20264.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}



data class DecryptedFile (
    var `content`: kotlin.ByteArray, 
    var `originalFilename`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeDecryptedFile: FfiConverterRustBuffer<DecryptedFile> {
    override fun read(buf: ByteBuffer): DecryptedFile {
        return DecryptedFile(
            FfiConverterByteArray.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: DecryptedFile) = (
            FfiConverterByteArray.allocationSize(value.`content`) +
            FfiConverterString.allocationSize(value.`originalFilename`)
    )

    override fun write(value: DecryptedFile, buf: ByteBuffer) {
            FfiConverterByteArray.write(value.`content`, buf)
            FfiConverterString.write(value.`originalFilename`, buf)
    }
}



data class DerivedKey (
    var `keyHex`: kotlin.String, 
    var `saltHex`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeDerivedKey: FfiConverterRustBuffer<DerivedKey> {
    override fun read(buf: ByteBuffer): DerivedKey {
        return DerivedKey(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: DerivedKey) = (
            FfiConverterString.allocationSize(value.`keyHex`) +
            FfiConverterString.allocationSize(value.`saltHex`)
    )

    override fun write(value: DerivedKey, buf: ByteBuffer) {
            FfiConverterString.write(value.`keyHex`, buf)
            FfiConverterString.write(value.`saltHex`, buf)
    }
}



data class Ov36Decoded (
    var `keyIndex`: kotlin.UInt, 
    var `payload`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeOv36Decoded: FfiConverterRustBuffer<Ov36Decoded> {
    override fun read(buf: ByteBuffer): Ov36Decoded {
        return Ov36Decoded(
            FfiConverterUInt.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: Ov36Decoded) = (
            FfiConverterUInt.allocationSize(value.`keyIndex`) +
            FfiConverterString.allocationSize(value.`payload`)
    )

    override fun write(value: Ov36Decoded, buf: ByteBuffer) {
            FfiConverterUInt.write(value.`keyIndex`, buf)
            FfiConverterString.write(value.`payload`, buf)
    }
}



data class Ov36Message (
    var `secureIndex`: kotlin.String, 
    var `plaintext`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeOv36Message: FfiConverterRustBuffer<Ov36Message> {
    override fun read(buf: ByteBuffer): Ov36Message {
        return Ov36Message(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: Ov36Message) = (
            FfiConverterString.allocationSize(value.`secureIndex`) +
            FfiConverterString.allocationSize(value.`plaintext`)
    )

    override fun write(value: Ov36Message, buf: ByteBuffer) {
            FfiConverterString.write(value.`secureIndex`, buf)
            FfiConverterString.write(value.`plaintext`, buf)
    }
}



data class OvAnnounce (
    var `ovbA`: kotlin.String, 
    var `stateHex`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeOvAnnounce: FfiConverterRustBuffer<OvAnnounce> {
    override fun read(buf: ByteBuffer): OvAnnounce {
        return OvAnnounce(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: OvAnnounce) = (
            FfiConverterString.allocationSize(value.`ovbA`) +
            FfiConverterString.allocationSize(value.`stateHex`)
    )

    override fun write(value: OvAnnounce, buf: ByteBuffer) {
            FfiConverterString.write(value.`ovbA`, buf)
            FfiConverterString.write(value.`stateHex`, buf)
    }
}



data class OvContactKey (
    var `contactKeyHex`: kotlin.String, 
    var `sas`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeOvContactKey: FfiConverterRustBuffer<OvContactKey> {
    override fun read(buf: ByteBuffer): OvContactKey {
        return OvContactKey(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: OvContactKey) = (
            FfiConverterString.allocationSize(value.`contactKeyHex`) +
            FfiConverterString.allocationSize(value.`sas`)
    )

    override fun write(value: OvContactKey, buf: ByteBuffer) {
            FfiConverterString.write(value.`contactKeyHex`, buf)
            FfiConverterString.write(value.`sas`, buf)
    }
}



data class OvHybridRespond (
    var `replySms`: kotlin.String, 
    var `contactKeyHex`: kotlin.String, 
    var `sas`: kotlin.String, 
    var `ssEcHex`: kotlin.String, 
    var `ssPqHex`: kotlin.String, 
    var `cipherTextHex`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeOvHybridRespond: FfiConverterRustBuffer<OvHybridRespond> {
    override fun read(buf: ByteBuffer): OvHybridRespond {
        return OvHybridRespond(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: OvHybridRespond) = (
            FfiConverterString.allocationSize(value.`replySms`) +
            FfiConverterString.allocationSize(value.`contactKeyHex`) +
            FfiConverterString.allocationSize(value.`sas`) +
            FfiConverterString.allocationSize(value.`ssEcHex`) +
            FfiConverterString.allocationSize(value.`ssPqHex`) +
            FfiConverterString.allocationSize(value.`cipherTextHex`)
    )

    override fun write(value: OvHybridRespond, buf: ByteBuffer) {
            FfiConverterString.write(value.`replySms`, buf)
            FfiConverterString.write(value.`contactKeyHex`, buf)
            FfiConverterString.write(value.`sas`, buf)
            FfiConverterString.write(value.`ssEcHex`, buf)
            FfiConverterString.write(value.`ssPqHex`, buf)
            FfiConverterString.write(value.`cipherTextHex`, buf)
    }
}



data class OvPairingOutcome (
    var `contactKeyHex`: kotlin.String, 
    var `sas`: kotlin.String, 
    var `myX25519PubHex`: kotlin.String, 
    var `mlkemCtHex`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeOvPairingOutcome: FfiConverterRustBuffer<OvPairingOutcome> {
    override fun read(buf: ByteBuffer): OvPairingOutcome {
        return OvPairingOutcome(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: OvPairingOutcome) = (
            FfiConverterString.allocationSize(value.`contactKeyHex`) +
            FfiConverterString.allocationSize(value.`sas`) +
            FfiConverterString.allocationSize(value.`myX25519PubHex`) +
            FfiConverterString.allocationSize(value.`mlkemCtHex`)
    )

    override fun write(value: OvPairingOutcome, buf: ByteBuffer) {
            FfiConverterString.write(value.`contactKeyHex`, buf)
            FfiConverterString.write(value.`sas`, buf)
            FfiConverterString.write(value.`myX25519PubHex`, buf)
            FfiConverterString.write(value.`mlkemCtHex`, buf)
    }
}



data class OvpkParsed (
    var `session`: kotlin.String, 
    var `role`: kotlin.String, 
    var `mlkemPkHex`: kotlin.String, 
    var `x25519PkHex`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeOvpkParsed: FfiConverterRustBuffer<OvpkParsed> {
    override fun read(buf: ByteBuffer): OvpkParsed {
        return OvpkParsed(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: OvpkParsed) = (
            FfiConverterString.allocationSize(value.`session`) +
            FfiConverterString.allocationSize(value.`role`) +
            FfiConverterString.allocationSize(value.`mlkemPkHex`) +
            FfiConverterString.allocationSize(value.`x25519PkHex`)
    )

    override fun write(value: OvpkParsed, buf: ByteBuffer) {
            FfiConverterString.write(value.`session`, buf)
            FfiConverterString.write(value.`role`, buf)
            FfiConverterString.write(value.`mlkemPkHex`, buf)
            FfiConverterString.write(value.`x25519PkHex`, buf)
    }
}



data class PairingInit (
    /**
     * Serialized secret keypair — the app stores this until B replies.
     */
    var `keypairHex`: kotlin.String, 
    /**
     * The `OVB:A:` SMS to send.
     */
    var `sms`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePairingInit: FfiConverterRustBuffer<PairingInit> {
    override fun read(buf: ByteBuffer): PairingInit {
        return PairingInit(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: PairingInit) = (
            FfiConverterString.allocationSize(value.`keypairHex`) +
            FfiConverterString.allocationSize(value.`sms`)
    )

    override fun write(value: PairingInit, buf: ByteBuffer) {
            FfiConverterString.write(value.`keypairHex`, buf)
            FfiConverterString.write(value.`sms`, buf)
    }
}



data class PairingResult (
    var `sharedKeyHex`: kotlin.String, 
    /**
     * Present only for party B — the `OVB:B:` SMS to send back.
     */
    var `sms`: kotlin.String?, 
    var `sas`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePairingResult: FfiConverterRustBuffer<PairingResult> {
    override fun read(buf: ByteBuffer): PairingResult {
        return PairingResult(
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: PairingResult) = (
            FfiConverterString.allocationSize(value.`sharedKeyHex`) +
            FfiConverterOptionalString.allocationSize(value.`sms`) +
            FfiConverterString.allocationSize(value.`sas`)
    )

    override fun write(value: PairingResult, buf: ByteBuffer) {
            FfiConverterString.write(value.`sharedKeyHex`, buf)
            FfiConverterOptionalString.write(value.`sms`, buf)
            FfiConverterString.write(value.`sas`, buf)
    }
}



data class SmsChunk (
    var `msgId`: kotlin.String, 
    var `seq`: kotlin.UInt, 
    var `total`: kotlin.UInt, 
    var `data`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSmsChunk: FfiConverterRustBuffer<SmsChunk> {
    override fun read(buf: ByteBuffer): SmsChunk {
        return SmsChunk(
            FfiConverterString.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: SmsChunk) = (
            FfiConverterString.allocationSize(value.`msgId`) +
            FfiConverterUInt.allocationSize(value.`seq`) +
            FfiConverterUInt.allocationSize(value.`total`) +
            FfiConverterString.allocationSize(value.`data`)
    )

    override fun write(value: SmsChunk, buf: ByteBuffer) {
            FfiConverterString.write(value.`msgId`, buf)
            FfiConverterUInt.write(value.`seq`, buf)
            FfiConverterUInt.write(value.`total`, buf)
            FfiConverterString.write(value.`data`, buf)
    }
}





sealed class FfiException: kotlin.Exception() {
    
    class Core(
        
        val `msg`: kotlin.String
        ) : FfiException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<FfiException> {
        override fun lift(error_buf: RustBuffer.ByValue): FfiException = FfiConverterTypeFfiError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiError : FfiConverterRustBuffer<FfiException> {
    override fun read(buf: ByteBuffer): FfiException {
        

        return when(buf.getInt()) {
            1 -> FfiException.Core(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: FfiException): ULong {
        return when(value) {
            is FfiException.Core -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
        }
    }

    override fun write(value: FfiException, buf: ByteBuffer) {
        when(value) {
            is FfiException.Core -> {
                buf.putInt(1)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeSmsChunk: FfiConverterRustBuffer<SmsChunk?> {
    override fun read(buf: ByteBuffer): SmsChunk? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeSmsChunk.read(buf)
    }

    override fun allocationSize(value: SmsChunk?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeSmsChunk.allocationSize(value)
        }
    }

    override fun write(value: SmsChunk?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeSmsChunk.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}
        /**
         * Party A: consume B's SMS and finish. `keypair_hex` is what `start_pairing_a`
         * returned.
         */
    @Throws(FfiException::class) fun `completePairingA`(`keypairHex`: kotlin.String, `bSms`: kotlin.String): PairingResult {
            return FfiConverterTypePairingResult.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_complete_pairing_a(
        FfiConverterString.lower(`keypairHex`),FfiConverterString.lower(`bSms`),_status)
}
    )
    }
    

    @Throws(FfiException::class) fun `decryptFile`(`keyHex`: kotlin.String, `ovBytes`: kotlin.ByteArray): DecryptedFile {
            return FfiConverterTypeDecryptedFile.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_decrypt_file(
        FfiConverterString.lower(`keyHex`),FfiConverterByteArray.lower(`ovBytes`),_status)
}
    )
    }
    

        /**
         * Argon2id. `salt_hex = None` mints a fresh salt; pass the stored salt to
         * reproduce the key on later logins.
         */
    @Throws(FfiException::class) fun `deriveFromPassword`(`password`: kotlin.String, `saltHex`: kotlin.String?): DerivedKey {
            return FfiConverterTypeDerivedKey.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_derive_from_password(
        FfiConverterString.lower(`password`),FfiConverterOptionalString.lower(`saltHex`),_status)
}
    )
    }
    

        /**
         * HKDF-derive the 500-key pool from the pairing master secret.
         */
    @Throws(FfiException::class) fun `deriveKeyPool`(`masterHex`: kotlin.String, `count`: kotlin.UInt): List<kotlin.String> {
            return FfiConverterSequenceString.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_derive_key_pool(
        FfiConverterString.lower(`masterHex`),FfiConverterUInt.lower(`count`),_status)
}
    )
    }
    

        /**
         * 12-hex SAS for out-of-band pairing verification.
         */
    @Throws(FfiException::class) fun `deriveSas`(`sharedHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_derive_sas(
        FfiConverterString.lower(`sharedHex`),_status)
}
    )
    }
    

    @Throws(FfiException::class) fun `encryptFile`(`keyHex`: kotlin.String, `content`: kotlin.ByteArray, `filename`: kotlin.String): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_encrypt_file(
        FfiConverterString.lower(`keyHex`),FfiConverterByteArray.lower(`content`),FfiConverterString.lower(`filename`),_status)
}
    )
    }
    

    @Throws(FfiException::class) fun `openMessage`(`poolKeyHex`: kotlin.String, `payload`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_open_message(
        FfiConverterString.lower(`poolKeyHex`),FfiConverterString.lower(`payload`),_status)
}
    )
    }
    

        /**
         * Decode a real OV Message `OV36:` frame to plaintext, using only the pairing
         * `contact_key_hex` (the byte-exact `ov36` codec — everything else is derived).
         */
    @Throws(FfiException::class) fun `ov36Decode`(`msg`: kotlin.String, `contactKeyHex`: kotlin.String): Ov36Message {
            return FfiConverterTypeOv36Message.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_ov36_decode(
        FfiConverterString.lower(`msg`),FfiConverterString.lower(`contactKeyHex`),_status)
}
    )
    }
    

        /**
         * Encode `plaintext` into an `OV36:` frame the OV Message app decodes, under the
         * pairing `contact_key_hex`. A fresh random secureIndex + nonce are generated.
         */
    @Throws(FfiException::class) fun `ov36Encode`(`plaintext`: kotlin.String, `contactKeyHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_ov36_encode(
        FfiConverterString.lower(`plaintext`),FfiConverterString.lower(`contactKeyHex`),_status)
}
    )
    }
    

        /**
         * Build an `OVPK:` announce from hex public keys.
         */
    @Throws(FfiException::class) fun `ovBuildOvpk`(`session`: kotlin.String, `role`: kotlin.String, `mlkemPkHex`: kotlin.String, `x25519PkHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_ov_build_ovpk(
        FfiConverterString.lower(`session`),FfiConverterString.lower(`role`),FfiConverterString.lower(`mlkemPkHex`),FfiConverterString.lower(`x25519PkHex`),_status)
}
    )
    }
    

        /**
         * Decode an OV36 message back to (key index, payload).
         */
    @Throws(FfiException::class) fun `ovDecodeOv36`(`msg`: kotlin.String, `indexCharset`: kotlin.String, `specialCharset`: kotlin.String): Ov36Decoded {
            return FfiConverterTypeOv36Decoded.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_ov_decode_ov36(
        FfiConverterString.lower(`msg`),FfiConverterString.lower(`indexCharset`),FfiConverterString.lower(`specialCharset`),_status)
}
    )
    }
    

        /**
         * Derive a permuted charset (index or special) from a session key, OV-exact.
         */ fun `ovDeriveCharset`(`base`: kotlin.String, `seedA`: kotlin.String, `seedB`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_ov_derive_charset(
        FfiConverterString.lower(`base`),FfiConverterString.lower(`seedA`),FfiConverterString.lower(`seedB`),_status)
}
    )
    }
    

        /**
         * Derive the OV-compatible per-contact key + SAS from a hybrid shared secret.
         */
    @Throws(FfiException::class) fun `ovDeriveContactKey`(`sharedSecretHex`: kotlin.String): OvContactKey {
            return FfiConverterTypeOvContactKey.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_ov_derive_contact_key(
        FfiConverterString.lower(`sharedSecretHex`),_status)
}
    )
    }
    

        /**
         * Encode an OV36 message: `OV36:<idx>><payload>` using OV-derived charsets.
         */
    @Throws(FfiException::class) fun `ovEncodeOv36`(`keyIndex`: kotlin.UInt, `payload`: kotlin.String, `indexCharset`: kotlin.String, `specialCharset`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_ov_encode_ov36(
        FfiConverterUInt.lower(`keyIndex`),FfiConverterString.lower(`payload`),FfiConverterString.lower(`indexCharset`),FfiConverterString.lower(`specialCharset`),_status)
}
    )
    }
    

        /**
         * Real OV SMS pairing responder: OVPK:<sess>:I:... in -> OVPK:<sess>:R:... reply
         * + contact key + SAS (noble ml_kem768_x25519 + OV HKDF).
         */
    @Throws(FfiException::class) fun `ovHybridRespond`(`ovpkSms`: kotlin.String): OvHybridRespond {
            return FfiConverterTypeOvHybridRespond.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_ov_hybrid_respond(
        FfiConverterString.lower(`ovpkSms`),_status)
}
    )
    }
    

        /**
         * OV handshake step 1 (responder): OVPK in -> OVB:A pk-announce + state.
         */
    @Throws(FfiException::class) fun `ovPairingAnnounce`(`ovpkMsg`: kotlin.String): OvAnnounce {
            return FfiConverterTypeOvAnnounce.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_ov_pairing_announce(
        FfiConverterString.lower(`ovpkMsg`),_status)
}
    )
    }
    

        /**
         * OV handshake step 2 (responder): state + OVB:B ciphertext -> contact key + SAS.
         */
    @Throws(FfiException::class) fun `ovPairingFinish`(`stateHex`: kotlin.String, `ovbBMsg`: kotlin.String): OvContactKey {
            return FfiConverterTypeOvContactKey.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_ov_pairing_finish(
        FfiConverterString.lower(`stateHex`),FfiConverterString.lower(`ovbBMsg`),_status)
}
    )
    }
    

        /**
         * Parse a real OV Message `OVPK:` pairing announce.
         */
    @Throws(FfiException::class) fun `ovParseOvpk`(`msg`: kotlin.String): OvpkParsed {
            return FfiConverterTypeOvpkParsed.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_ov_parse_ovpk(
        FfiConverterString.lower(`msg`),_status)
}
    )
    }
    

        /**
         * Full OV pairing responder: consume OV's announced ML-KEM encaps key + X25519
         * pub (from an `OVPK:`), run X25519 DH + ML-KEM-768 encaps + noble KitchenSink
         * combine + OV HKDF -> the same per-contact key OV derives, plus the ciphertext
         * and X25519 pub to send back.
         */
    @Throws(FfiException::class) fun `ovRespondPairing`(`mlkemEkHex`: kotlin.String, `x25519PubHex`: kotlin.String): OvPairingOutcome {
            return FfiConverterTypeOvPairingOutcome.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_ov_respond_pairing(
        FfiConverterString.lower(`mlkemEkHex`),FfiConverterString.lower(`x25519PubHex`),_status)
}
    )
    }
    
 fun `parseChunk`(`sms`: kotlin.String): SmsChunk? {
            return FfiConverterOptionalTypeSmsChunk.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_parse_chunk(
        FfiConverterString.lower(`sms`),_status)
}
    )
    }
    

    @Throws(FfiException::class) fun `peekKeyIndex`(`payload`: kotlin.String): kotlin.UInt {
            return FfiConverterUInt.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_peek_key_index(
        FfiConverterString.lower(`payload`),_status)
}
    )
    }
    

        /**
         * A fresh random 32-byte key as hex (OS CSPRNG). For manually-keyed contacts.
         */ fun `randomKeyHex`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_random_key_hex(
        _status)
}
    )
    }
    

        /**
         * Party B: consume A's SMS, derive the shared key, and produce the reply.
         */
    @Throws(FfiException::class) fun `respondPairingB`(`aSms`: kotlin.String): PairingResult {
            return FfiConverterTypePairingResult.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_respond_pairing_b(
        FfiConverterString.lower(`aSms`),_status)
}
    )
    }
    

    @Throws(FfiException::class) fun `sealMessage`(`poolKeyHex`: kotlin.String, `keyIndex`: kotlin.UInt, `plaintext`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(FfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_seal_message(
        FfiConverterString.lower(`poolKeyHex`),FfiConverterUInt.lower(`keyIndex`),FfiConverterString.lower(`plaintext`),_status)
}
    )
    }
    
 fun `splitIntoChunks`(`payload`: kotlin.String, `msgId`: kotlin.String, `maxLen`: kotlin.UInt): List<kotlin.String> {
            return FfiConverterSequenceString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_split_into_chunks(
        FfiConverterString.lower(`payload`),FfiConverterString.lower(`msgId`),FfiConverterUInt.lower(`maxLen`),_status)
}
    )
    }
    

        /**
         * Party A: start pairing. Returns the keypair to persist + the SMS to send.
         */ fun `startPairingA`(): PairingInit {
            return FfiConverterTypePairingInit.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_ov_core_fn_func_start_pairing_a(
        _status)
}
    )
    }
    


